"""Helpers used by repository notebooks."""

from notebooks.helpers.party_primary_strategy_space import (
    DISPLAY_LABELS as PARTY_SPACE_DISPLAY_LABELS,
    ELECTORATE_ORDER as PARTY_SPACE_ELECTORATE_ORDER,
    PRIMARY_ORDER as PARTY_SPACE_PRIMARY_ORDER,
    RATIO_ORDER as PARTY_SPACE_RATIO_ORDER,
    SLATE_ORDER as PARTY_SPACE_SLATE_ORDER,
    STRATEGY_ORDER as PARTY_SPACE_STRATEGY_ORDER,
    SYSTEM_ORDER as PARTY_SPACE_SYSTEM_ORDER,
    TURNOUT_ORDER as PARTY_SPACE_TURNOUT_ORDER,
    build_candidate_slate as build_party_space_candidate_slate,
    build_grouped_electorate as build_party_space_electorate,
    build_party_positions,
    build_turnout_setup,
    full_space_helper_overview,
    plot_party_snapshot,
    run_design_case,
    run_full_space_grid,
)
from notebooks.helpers.polarization_dynamics import (
    CANDIDATE_MODEL_ORDER as POLARIZATION_CANDIDATE_MODEL_ORDER,
    CANDIDATE_ORDER as POLARIZATION_CANDIDATE_ORDER,
    DISPLAY_LABELS as POLARIZATION_DISPLAY_LABELS,
    ELECTORATE_ORDER as POLARIZATION_ELECTORATE_ORDER,
    ORACLE_ORDER as POLARIZATION_ORACLE_ORDER,
    RATIO_ORDER as POLARIZATION_RATIO_ORDER,
    SYSTEM_ORDER as POLARIZATION_SYSTEM_ORDER,
    VOTER_MODEL_ORDER as POLARIZATION_VOTER_MODEL_ORDER,
    advance_candidates,
    advance_voters,
    build_candidate_dynamics,
    build_polarization_candidates,
    build_polarization_electorate,
    build_system as build_polarization_system,
    build_voter_dynamics,
    choose_oracle_outcome,
    compare_trajectory_to_baseline,
    compute_camp_asymmetry_metrics,
    compute_next_step_polarization,
    compute_polarization_metrics,
    compute_voter_variance as compute_dynamic_voter_variance,
    fractional_sigma_name,
    illustrate_candidate_mechanisms,
    illustrate_voter_mechanisms,
    parse_fractional_sigma,
    plot_baseline_difference_trajectories,
    plot_fractional_sigma_sweep,
    plot_oracle_start_end_maps,
    plot_polarization_trajectories,
    plot_polarization_metric_heatmap,
    plot_polarization_tradeoff_scatter,
    plot_ratio_system_heatmap,
    plot_start_end_maps,
    polarization_helper_overview,
    run_polarization_comparison_grid,
    run_oracle_trajectory,
    run_polarization_trajectory,
    run_polarization_trajectory_grid,
    summarize_fractional_sigma_sweep,
    summarize_trajectory_changes,
    trace_oracle_state,
)
from notebooks.helpers.cross_group_welfare_lhs import (
    lhs_helper_overview,
    plot_lhs_case_gallery,
    plot_lhs_metric_map,
    plot_lhs_monte_carlo,
    plot_lhs_parameter_coverage,
    plot_lhs_system_summary,
    run_lhs_grid,
    run_selected_lhs_monte_carlo,
    sample_latin_hypercube_design,
    select_interesting_lhs_cases,
    summarize_lhs_monte_carlo,
    summarize_lhs_systems,
)
from notebooks.helpers.cross_group_welfare import (
    DISPERSION_ORDER,
    DISPLAY_LABELS as CROSS_GROUP_DISPLAY_LABELS,
    OVERLAP_ORDER,
    RATIO_ORDER,
    SLATE_ORDER,
    SYSTEM_ORDER,
    build_candidate_slate,
    build_two_group_electorate,
    candidate_support_table,
    case_record,
    group_welfare_decomposition,
    helper_overview as cross_group_helper_overview,
    overlap_counterfactual_table,
    plot_candidate_slate_gallery,
    plot_condition_heatmaps,
    plot_electorate_gallery,
    plot_representative_divergence_cases,
    plot_system_summary,
    representative_divergence_cases,
    run_case_systems,
    run_full_grid as run_cross_group_grid,
    summarize_condition_patterns,
    summarize_system_patterns,
    top_alignment_cases,
    top_divergence_cases,
)
from notebooks.helpers.electoral_dynamics_theory import (
    CANDIDATE_MODEL_ORDER as THEORY_CANDIDATE_MODEL_ORDER,
    CANDIDATE_ORDER as THEORY_CANDIDATE_ORDER,
    ELECTORATE_ORDER as THEORY_ELECTORATE_ORDER,
    RATIO_ORDER as THEORY_RATIO_ORDER,
    THEORY_BASELINE_SYSTEMS,
    THEORY_MU0_CANDIDATE_MODELS,
    THEORY_ORACLE_ORDER,
    VOTER_MODEL_ORDER as THEORY_VOTER_MODEL_ORDER,
    approximate_minimax_center,
    build_fractional_tradeoff_cases,
    build_theory_candidate_dynamics,
    build_theory_system,
    compute_candidate_variance,
    compute_candidate_electorate_center_gap,
    compute_coverage_gap,
    compute_mean_supporter_centroid_distance,
    compute_next_step_voter_variance,
    compute_mean_winner_distance,
    compute_supporter_centroid_radius,
    compute_supporter_centroids,
    compute_theory_metrics,
    compute_voter_variance,
    compute_weighted_polarization_cost,
    compute_winner_radius,
    choose_theory_oracle_outcome,
    distance_to_candidate_convex_hull,
    fractional_continuous_name,
    parse_fractional_continuous_sigma,
    plot_fractional_weighted_objective_curves,
    run_theory_grid,
    run_theory_oracle_trajectory,
    run_theory_trajectory,
    search_fractional_interior_optima,
    summarize_asymmetry_by_system,
    summarize_fractional_continuous_sweep as summarize_theory_fractional_continuous_sweep,
    summarize_theory_trajectory_changes,
    supporter_weight_matrix,
    trace_theory_oracle_state,
    theory_helper_overview,
)
from notebooks.helpers.primaries_moderation_backfire import (
    CANDIDATE_ORDER,
    DISPLAY_LABELS,
    PIPELINE_ORDER,
    TURNOUT_ORDER,
    VOTER_ORDER,
    build_candidate_profile,
    build_voter_profile,
    pipeline_overview,
    plot_deep_dive,
    plot_metric_small_multiples,
    plot_turnout_snapshot,
    run_full_grid,
    summarize_full_grid,
)

__all__ = [
    "VOTER_ORDER",
    "CANDIDATE_ORDER",
    "TURNOUT_ORDER",
    "PIPELINE_ORDER",
    "DISPLAY_LABELS",
    "build_voter_profile",
    "build_candidate_profile",
    "run_full_grid",
    "summarize_full_grid",
    "pipeline_overview",
    "plot_turnout_snapshot",
    "plot_metric_small_multiples",
    "plot_deep_dive",
    "RATIO_ORDER",
    "OVERLAP_ORDER",
    "DISPERSION_ORDER",
    "SLATE_ORDER",
    "SYSTEM_ORDER",
    "CROSS_GROUP_DISPLAY_LABELS",
    "build_two_group_electorate",
    "build_candidate_slate",
    "case_record",
    "run_cross_group_grid",
    "run_case_systems",
    "summarize_system_patterns",
    "summarize_condition_patterns",
    "cross_group_helper_overview",
    "plot_electorate_gallery",
    "plot_candidate_slate_gallery",
    "plot_system_summary",
    "plot_condition_heatmaps",
    "top_divergence_cases",
    "top_alignment_cases",
    "representative_divergence_cases",
    "plot_representative_divergence_cases",
    "group_welfare_decomposition",
    "candidate_support_table",
    "overlap_counterfactual_table",
    "THEORY_ELECTORATE_ORDER",
    "THEORY_RATIO_ORDER",
    "THEORY_CANDIDATE_ORDER",
    "THEORY_VOTER_MODEL_ORDER",
    "THEORY_CANDIDATE_MODEL_ORDER",
    "THEORY_BASELINE_SYSTEMS",
    "THEORY_MU0_CANDIDATE_MODELS",
    "THEORY_ORACLE_ORDER",
    "theory_helper_overview",
    "fractional_continuous_name",
    "parse_fractional_continuous_sigma",
    "build_fractional_tradeoff_cases",
    "build_theory_candidate_dynamics",
    "build_theory_system",
    "choose_theory_oracle_outcome",
    "supporter_weight_matrix",
    "compute_supporter_centroids",
    "compute_winner_radius",
    "compute_mean_winner_distance",
    "compute_voter_variance",
    "compute_candidate_variance",
    "compute_candidate_electorate_center_gap",
    "compute_supporter_centroid_radius",
    "compute_mean_supporter_centroid_distance",
    "compute_theory_metrics",
    "compute_weighted_polarization_cost",
    "compute_next_step_voter_variance",
    "approximate_minimax_center",
    "distance_to_candidate_convex_hull",
    "compute_coverage_gap",
    "trace_theory_oracle_state",
    "run_theory_oracle_trajectory",
    "run_theory_trajectory",
    "summarize_theory_trajectory_changes",
    "run_theory_grid",
    "summarize_asymmetry_by_system",
    "search_fractional_interior_optima",
    "summarize_theory_fractional_continuous_sweep",
    "plot_fractional_weighted_objective_curves",
    "sample_latin_hypercube_design",
    "lhs_helper_overview",
    "run_lhs_grid",
    "summarize_lhs_systems",
    "plot_lhs_parameter_coverage",
    "plot_lhs_case_gallery",
    "plot_lhs_system_summary",
    "plot_lhs_metric_map",
    "select_interesting_lhs_cases",
    "run_selected_lhs_monte_carlo",
    "summarize_lhs_monte_carlo",
    "plot_lhs_monte_carlo",
    "PARTY_SPACE_RATIO_ORDER",
    "PARTY_SPACE_ELECTORATE_ORDER",
    "PARTY_SPACE_PRIMARY_ORDER",
    "PARTY_SPACE_TURNOUT_ORDER",
    "PARTY_SPACE_STRATEGY_ORDER",
    "PARTY_SPACE_SLATE_ORDER",
    "PARTY_SPACE_SYSTEM_ORDER",
    "PARTY_SPACE_DISPLAY_LABELS",
    "build_party_positions",
    "build_party_space_electorate",
    "build_party_space_candidate_slate",
    "build_turnout_setup",
    "full_space_helper_overview",
    "plot_party_snapshot",
    "run_design_case",
    "run_full_space_grid",
    "POLARIZATION_ELECTORATE_ORDER",
    "POLARIZATION_CANDIDATE_ORDER",
    "POLARIZATION_RATIO_ORDER",
    "POLARIZATION_VOTER_MODEL_ORDER",
    "POLARIZATION_CANDIDATE_MODEL_ORDER",
    "POLARIZATION_SYSTEM_ORDER",
    "POLARIZATION_ORACLE_ORDER",
    "POLARIZATION_DISPLAY_LABELS",
    "build_polarization_electorate",
    "build_polarization_candidates",
    "build_voter_dynamics",
    "build_candidate_dynamics",
    "choose_oracle_outcome",
    "fractional_sigma_name",
    "build_polarization_system",
    "compute_polarization_metrics",
    "compute_camp_asymmetry_metrics",
    "compute_next_step_polarization",
    "compute_dynamic_voter_variance",
    "compare_trajectory_to_baseline",
    "advance_voters",
    "advance_candidates",
    "run_oracle_trajectory",
    "run_polarization_trajectory",
    "run_polarization_trajectory_grid",
    "trace_oracle_state",
    "parse_fractional_sigma",
    "plot_polarization_trajectories",
    "plot_baseline_difference_trajectories",
    "plot_fractional_sigma_sweep",
    "plot_oracle_start_end_maps",
    "summarize_trajectory_changes",
    "summarize_fractional_sigma_sweep",
    "run_polarization_comparison_grid",
    "plot_polarization_metric_heatmap",
    "plot_polarization_tradeoff_scatter",
    "plot_ratio_system_heatmap",
    "illustrate_voter_mechanisms",
    "illustrate_candidate_mechanisms",
    "plot_start_end_maps",
    "polarization_helper_overview",
]
