"""Helpers used by repository notebooks."""

from notebooks.helpers.party_primary_strategy_space import (
    DISPLAY_LABELS as PARTY_SPACE_DISPLAY_LABELS,
    ELECTORATE_ORDER as PARTY_SPACE_ELECTORATE_ORDER,
    PRIMARY_ORDER as PARTY_SPACE_PRIMARY_ORDER,
    RATIO_ORDER as PARTY_SPACE_RATIO_ORDER,
    SLATE_ORDER as PARTY_SPACE_SLATE_ORDER,
    STRATEGY_ORDER as PARTY_SPACE_STRATEGY_ORDER,
    SYSTEM_ORDER as PARTY_SPACE_SYSTEM_ORDER,
    TURNOUT_ORDER as PARTY_SPACE_TURNOUT_ORDER,
    build_candidate_slate as build_party_space_candidate_slate,
    build_grouped_electorate as build_party_space_electorate,
    build_party_positions,
    build_turnout_setup,
    full_space_helper_overview,
    plot_party_snapshot,
    run_design_case,
    run_full_space_grid,
)
from notebooks.helpers.cross_group_welfare_lhs import (
    lhs_helper_overview,
    plot_lhs_case_gallery,
    plot_lhs_metric_map,
    plot_lhs_monte_carlo,
    plot_lhs_parameter_coverage,
    plot_lhs_system_summary,
    run_lhs_grid,
    run_selected_lhs_monte_carlo,
    sample_latin_hypercube_design,
    select_interesting_lhs_cases,
    summarize_lhs_monte_carlo,
    summarize_lhs_systems,
)
from notebooks.helpers.cross_group_welfare import (
    DISPERSION_ORDER,
    DISPLAY_LABELS as CROSS_GROUP_DISPLAY_LABELS,
    OVERLAP_ORDER,
    RATIO_ORDER,
    SLATE_ORDER,
    SYSTEM_ORDER,
    build_candidate_slate,
    build_two_group_electorate,
    candidate_support_table,
    case_record,
    group_welfare_decomposition,
    helper_overview as cross_group_helper_overview,
    overlap_counterfactual_table,
    plot_candidate_slate_gallery,
    plot_condition_heatmaps,
    plot_electorate_gallery,
    plot_representative_divergence_cases,
    plot_system_summary,
    representative_divergence_cases,
    run_case_systems,
    run_full_grid as run_cross_group_grid,
    summarize_condition_patterns,
    summarize_system_patterns,
    top_alignment_cases,
    top_divergence_cases,
)
from notebooks.helpers.primaries_moderation_backfire import (
    CANDIDATE_ORDER,
    DISPLAY_LABELS,
    PIPELINE_ORDER,
    TURNOUT_ORDER,
    VOTER_ORDER,
    build_candidate_profile,
    build_voter_profile,
    pipeline_overview,
    plot_deep_dive,
    plot_metric_small_multiples,
    plot_turnout_snapshot,
    run_full_grid,
    summarize_full_grid,
)

__all__ = [
    "VOTER_ORDER",
    "CANDIDATE_ORDER",
    "TURNOUT_ORDER",
    "PIPELINE_ORDER",
    "DISPLAY_LABELS",
    "build_voter_profile",
    "build_candidate_profile",
    "run_full_grid",
    "summarize_full_grid",
    "pipeline_overview",
    "plot_turnout_snapshot",
    "plot_metric_small_multiples",
    "plot_deep_dive",
    "RATIO_ORDER",
    "OVERLAP_ORDER",
    "DISPERSION_ORDER",
    "SLATE_ORDER",
    "SYSTEM_ORDER",
    "CROSS_GROUP_DISPLAY_LABELS",
    "build_two_group_electorate",
    "build_candidate_slate",
    "case_record",
    "run_cross_group_grid",
    "run_case_systems",
    "summarize_system_patterns",
    "summarize_condition_patterns",
    "cross_group_helper_overview",
    "plot_electorate_gallery",
    "plot_candidate_slate_gallery",
    "plot_system_summary",
    "plot_condition_heatmaps",
    "top_divergence_cases",
    "top_alignment_cases",
    "representative_divergence_cases",
    "plot_representative_divergence_cases",
    "group_welfare_decomposition",
    "candidate_support_table",
    "overlap_counterfactual_table",
    "sample_latin_hypercube_design",
    "lhs_helper_overview",
    "run_lhs_grid",
    "summarize_lhs_systems",
    "plot_lhs_parameter_coverage",
    "plot_lhs_case_gallery",
    "plot_lhs_system_summary",
    "plot_lhs_metric_map",
    "select_interesting_lhs_cases",
    "run_selected_lhs_monte_carlo",
    "summarize_lhs_monte_carlo",
    "plot_lhs_monte_carlo",
    "PARTY_SPACE_RATIO_ORDER",
    "PARTY_SPACE_ELECTORATE_ORDER",
    "PARTY_SPACE_PRIMARY_ORDER",
    "PARTY_SPACE_TURNOUT_ORDER",
    "PARTY_SPACE_STRATEGY_ORDER",
    "PARTY_SPACE_SLATE_ORDER",
    "PARTY_SPACE_SYSTEM_ORDER",
    "PARTY_SPACE_DISPLAY_LABELS",
    "build_party_positions",
    "build_party_space_electorate",
    "build_party_space_candidate_slate",
    "build_turnout_setup",
    "full_space_helper_overview",
    "plot_party_snapshot",
    "run_design_case",
    "run_full_space_grid",
]
